apiVersion: v1
kind: Pod
metadata:
  name: aipod
  labels:
    app: aipod
spec:
  containers:
    - name: aipod
      image: aipod
      ports:
        - containerPort: 8000
      imagePullPolicy: IfNotPresent
      env:
        - name: MODEL
          value: "llama3.2"
        - name: TOKEN
          value: ""
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aipod
  name: aipod
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30008
  selector:
    app: aipod
