apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - image: ollama/ollama:latest
          name: ollama
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: 4000m
              memory: 2Gi
            limits:
              cpu: 8000m
              memory: 10Gi
        - image: curlimages/curl
          name: load-model
          command: ["/bin/sh", "-c"]
          args:
            - "sleep infinity"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - 'curl -X POST http://localhost:11434/api/pull -H ''Content-Type: application/json'' -d ''{"name": "llama3.2:1b"}'''
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: ollama
spec:
  type: NodePort
  ports:
    - port: 11434
      nodePort: 30007
  selector:
    app: ollama
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama1
  namespace: ollama
spec:
  clusterIP: None # <= Don't forget!!
  ports:
    - port: 11434
  selector:
    app: ollama
